### ISSUE TITLE
Properties class or Json ?

### ISSUE THREAD

**Issue by trofleb** [zifeo/Planair#18]
It'd be useful to centralise all the parameters of the game in a class or a Json file.

Good idea ? or overdoing it ?

**Comment by zifeo** [comment]
Very good idea :) JSON would be appropriate.
Is there any good JSON library out there ?

**Comment by trofleb** [comment]
org.json simple enough for what we have to do.

**Comment by zifeo** [comment]
Sounds great :D

**Comment by timozattol** [comment]
Seems like we simply went for a class
