### ISSUE TITLE
Scala or Java ? 

### ISSUE THREAD

**Issue by timozattol** [zifeo/Planair#3]
I saw you set up the project with Scala files, is it okay with the prof / assistants ? I'm okay to do scala but we need to be sure it's possible with Processing and everything.

**Comment by zifeo** [comment]
The teaching team has to confirm this point next week so we will decide later.
We checked Processing and Scala last hour and everything was okay.

**Comment by zifeo** [comment]
Java for mandatory part as it is more easy.
