### ISSUE TITLE
Replace Pipeline class by PipelineOnplace

### ISSUE THREAD

**Issue by timozattol** [zifeo/Planair#31]
- Remove Pipeline
- Rename PipelineOnplace to Pipeline :wink:

**Comment by zifeo** [comment]
We should keep it for further work (milestone 4).

**Comment by timozattol** [comment]
@zifeo what cannot we do with a on-place pipeline that we can do with a "copy" pipeline? We can still copy the image between the pipeline steps right?

**Comment by timozattol** [comment]
Since it's exactly the same code I think it's easier to maintain only one version, we'll avoid bugs due to something that changed in one implementation and not the other.

**Comment by zifeo** [comment]
We may have some more operations to do « manually » for next milestone.
And pipeline on place is going to be fastened a bit more (and could get less readable…).

**Comment by timozattol** [comment]
Okay then
