### ISSUE TITLE
Display the image of the webcam

### ISSUE THREAD

**Issue by timozattol** [zifeo/Planair#35]
- Display in live an image of the webcam, to know if you're holding the plate in the right position
- If it is too ressource-demanding, do it only in debug mode

**Comment by zifeo** [comment]
Not possible for performance and flux transmission, but we could put the corners when detected.

**Comment by timozattol** [comment]
@zifeo what do you mean by "put the corners when detected"? Display them on the 3D game? It's gonna feel awkward, no?

**Comment by zifeo** [comment]
Agreed, I already implemented something similar in the cam setup.

**Comment by timozattol** [comment]
Yep in the cam setup it's perfect! Let's forget about a in-game webcam feedback for now, maybe later
