### ISSUE TITLE
Scorable as Interface

### ISSUE THREAD

**Issue by timozattol** [zifeo/Planair#37]
I think Scorable should be an Inferface, it doesn't make lots of sense that it extends "Accelerable".

**Comment by zifeo** [comment]
As there is no multiple heritage, this is the only solution.
A scorable is something that moves and scores with its characterics thus also an accelerable.

**Comment by timozattol** [comment]
Meh... I see but to me Accelerable and Scorable are two totally different things thus it's weird to use a "IS A" relationship between them. I would rather use an Interface for Scorable with abstract methods addScoreObserver and notifyScore in the Sphere for example, but whatever this is not so important at that point :)
